name: appkit_ui_elements
description: "Flutter widgets and themes for the current macOS desktop. It was inspired by the great [macos_ui](https://pub.dev/packages/macos_ui) library."
version: 0.0.22
homepage: https://github.com/sephiroth74/appkit_ui_elements
repository: https://github.com/sephiroth74/appkit_ui_elements


environment:
  sdk: ^3.5.4
  flutter: ">=1.20.0"

dependencies:
  appkit_ui_element_colors: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  gradient_borders: ^1.0.1
  macos_window_utils: ^1.6.0
  rxdart: ^0.28.0
  system_theme: ^3.1.2
  uuid: ^4.5.1
  plugin_platform_interface: ^2.1.8
  collection: ^1.18.0
  indexed: ^0.0.8
  dartz: ^0.10.1
  intl: ">=0.19.0"
  provider: ^6.1.2
  logging: ^1.3.0
  window_manager: ^0.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/
    - assets/components/checkbox/
  plugin:
    platforms:
      macos:
        package: dev.sephiroth74.appkit_ui_elements
        pluginClass: AppKitUiElementsPlugin
